// <auto-generated />
using MDM_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDM_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MDM_API.Models.ChuyenXe", b =>
                {
                    b.Property<int>("MaChuyenXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenXe"));

                    b.Property<string>("TenChuyenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChuyenXe");

                    b.ToTable("ChuyenXe");

                    b.HasData(
                        new
                        {
                            MaChuyenXe = 1,
                            TenChuyenXe = "Chuyen Xe 1"
                        },
                        new
                        {
                            MaChuyenXe = 2,
                            TenChuyenXe = "Chuyen Xe 2"
                        },
                        new
                        {
                            MaChuyenXe = 3,
                            TenChuyenXe = "Chuyen Xe 3"
                        },
                        new
                        {
                            MaChuyenXe = 4,
                            TenChuyenXe = "Chuyen Xe 4"
                        },
                        new
                        {
                            MaChuyenXe = 5,
                            TenChuyenXe = "Chuyen Xe 5"
                        });
                });

            modelBuilder.Entity("MDM_API.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Email = "admin@gmail.com",
                            DiaChi = "HCM",
                            GioiTinh = 1,
                            HoTen = "",
                            MatKhau = "123",
                            NgaySinh = "1/1/2024",
                            NgheNghiep = "",
                            SDT = "123456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
